### ISSUE TITLE
Windows 10 application using quantumjava, strange, strangefx gets graphics errors

### ISSUE THREAD

**Issue by mik3hall** [johanvos/quantumjava#26]
I'm not sure if you're interested in the code running as an application but if so this has had an issue below.

I have tried this Windows 10 virtual box and on a old Mac laptop I copied Windows 10 over the top of, same error.
Google shows others have had the issue and I saw different claims that different modular parts would fix it, but have had no success. I even looked at what GitHub quantumjava maven does and believe I have tried the matching parameters.

This was more successful on OS/X. Again if of any interest and you have access to a Mac I have put most of the pertinent parts in a dmg at http://mikehall.pairserver.com/qc.dmg. Not signed at all so it may give some grief over that. I can sign the app if needed. 
It had problems with maryqubit being started as a second application. So I set that to run as a separate process. That runs it but I have figured out how to get the process to exit cleanly. There are some rendering issues. Missing wires, ones with probabilty gates don't seem to appear right. Some of the other later ones look off. But they all run.

 For changes I have considered. I had a little difficulty understanding the probability gate. Probably because I looked at the rendering before being clear on the text. I was thinking the cells would somehow correspond to the qubit's they were across from. Where actually each cell represents the states of all cells? I was thinking a popup on clicking one of the cells could give you more information. 

For displaying the qubit states I was also thinking something like this...
https://stackoverflow.com/questions/68903791/javafx-circle-linear-gradient-fill-by-percentage
maybe better visualized my understanding of superposition. I was thinking of maybe trying to add a property that would allow this visualization to be selected.

An easy new feature would be a file menu that allowed to open, read, compile, run and render a user java program.
Sort of a start at an IDE?

Considerably more involved IDE like would be making this javafx scene builder like. Have an interface where you could visually drag qubits, gates, wires, oracles... and from that generate XML. From the XML the java quantum circuit boilerplate could be generated. With XML being language independent you could possibly generate boilerplate for other languages - python, c++, qasm. Since this is just for the quantum circuitry it might not be exceedingly complex. A thought. 

my 2 cents anyhow.

The actual windows error issue follows. I may continue with some of this on OS/X but taking a break for now.

Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:263)
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1081)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at javafx.graphics@20.0.2/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1081)
Caused by: java.lang.RuntimeException: No toolkit found
	at javafx.graphics@20.0.2/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:275)
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
	at javafx.graphics@20.0.2/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
	at javafx.graphics@20.0.2/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 2 more

**Comment by mik3hall** [comment]
This was probably an error in my jpackage invocation to build the jre for javafx. I just did it successfully for a current version of my strange/strangefx based application for both Windows 11 and Ubuntu 25. 
This can be closed with nothing more needing to be done.
